//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHARE_REST_API_v1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHARE_DBEntities : DbContext
    {
        public CHARE_DBEntities()
            : base("name=CHARE_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<CarModel2> CarModel2 { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<TripDriver> TripDrivers { get; set; }
        public virtual DbSet<TripPassenger> TripPassengers { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
