//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHARE_REST_API_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RateID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> RaterID { get; set; }
        public string comment { get; set; }
        public Nullable<int> rate { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
