//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHARE_REST_API_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int RequestID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string status { get; set; }
    
        public virtual TripDriver TripDriver { get; set; }
        public virtual TripPassenger TripPassenger { get; set; }
    }
}
