//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHARE_REST_API_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripPassenger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripPassenger()
        {
            this.Requests = new HashSet<Request>();
        }
    
        public int TripPassengerID { get; set; }
        public Nullable<int> PassengerID { get; set; }
        public Nullable<int> TripDriverID { get; set; }
        public string originLatLng { get; set; }
        public string destinationLatLng { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public System.TimeSpan arriveTime { get; set; }
        public string femaleOnly { get; set; }
        public Nullable<double> cost { get; set; }
        public Nullable<double> distance { get; set; }
        public Nullable<int> duration { get; set; }
        public string costStr { get; set; }
        public string distanceStr { get; set; }
        public string durationStr { get; set; }
        public string days { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        public virtual TripDriver TripDriver { get; set; }
    }
}
