//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHARE_REST_API_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string color { get; set; }
        public string plateNo { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
